---
apiVersion: v1
kind: Service
metadata:
  name: pihole-http
  labels:
    app.kubernetes.io/name: pihole
spec:
  type: LoadBalancer 
  externalTrafficPolicy: Local
  ports:
    - port: 8080
      targetPort: 80 
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pihole 
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp 
  labels:
    app.kubernetes.io/name: pihole
spec:
  type: LoadBalancer 
  externalTrafficPolicy: Local
  ports:
    - port: 53 
      targetPort: 53 
      protocol: TCP 
      name: dnstcp 
  selector:
    app.kubernetes.io/name: pihole 
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  labels:
    app.kubernetes.io/name: pihole
spec:
  type: LoadBalancer 
  externalTrafficPolicy: Local
  ports:
    - port: 53 
      targetPort: 53 
      protocol: UDP 
      name: dnsudp 
  selector:
    app.kubernetes.io/name: pihole 

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: pihole 
  namespace: pihole
  labels:
    app: pihole 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pihole 
    spec:
      containers:
      - name: pihole 
        image: pihole/pihole:2023.05.2
        env:
          - name: TZ
            value: "America/Chicago"
          - name: WEBPASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: WEBPASSWORD
        ports:
          - containerPort: 53
            protocol: TCP
            name: dnstcp
          - containerPort: 53
            protocol: UDP
            name: dnsudp
          - containerPort: 80
            protocol: TCP
            name: http 
        volumeMounts:
          - name: etc
            mountPath: /etc/pihole
          - name: dnsmasq
            mountPath: /etc/dnsmasq.d
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1
      volumes:
        - name: etc
          hostPath:
            path: /var/lib/pihole/etc
            type: Directory
        - name: dnsmasq
          hostPath:
            path: /var/lib/pihole/dnsmasq.d
            type: Directory


